# Site settings
title: Reclama
email: bravebox@gmail.com
description: "We are Creativity. Reclama is een Rotterdams agentschap van creatieve ondernemers."
baseurl: ""
url: "http://www.reclama.nl"

address: "Goudsesingle 70 Unit 3.74"
postalcode: "3011 KD"
town: "Rotterdam"
country: "Nederland"

# Build settings
exclude: ['config.rb', '.sass-cache/', '.temp/', 'sass/', 'scripts/']
markdown: kramdown
permalink: pretty
