# Site settings
title: Reclama
email: bravebox@gmail.com
description: "We are Creativity. Reclama is een Rotterdams agentschap van creatieve ondernemers."
baseurl: ""
url: "http://www.reclama.nl"
twitter_username: bravebox
github_username:  bravebox

# Build settings
markdown: kramdown
permalink: pretty
